name: Assignment Email Check

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  email-check:
    runs-on: ubuntu-latest
    steps:
      - name: "25f1002053@ds.study.iitm.ac.in"
        run: echo "Hello, world!"
